### ISSUE TITLE
Missing LICENSE?

### ISSUE THREAD

**Issue by decause** [TeCoEd/Rock-Paper-Scissors-Lizard-Spock-Sense-HAT-style_#1]
Thank you for sharing your code with the FOSS community :)

Out of curiosity, if someone wanted to modify or contribute to your codebase, which Free/Open Source Software license are you are releasing your code under? Perhaps I missed it, but I didn't see it in your README file, headers in your code, or in the main repository.

Many Thanks,
--RemyD.

**Comment by TeCoEd** [comment]
Well spotted I had missed it.
Added now
Thanks for the heads up
